# Generated by Django 3.1.4 on 2020-12-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'ariplanes',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_name', models.CharField(max_length=16)),
                ('english_name', models.CharField(max_length=32)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country')),
            ],
            options={
                'db_table': 'airports',
            },
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=8)),
                ('premium', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'calenders',
            },
        ),
        migrations.CreateModel(
            name='CalenderPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.calender')),
            ],
            options={
                'db_table': 'calender_pirces',
            },
        ),
        migrations.CreateModel(
            name='FlightImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'flight_images',
            },
        ),
        migrations.CreateModel(
            name='PassengerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'passenger_informations',
            },
        ),
        migrations.CreateModel(
            name='PathType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'path_types',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('image_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='UserPassengerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.passengerinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'user_passenger_informations',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_amounts', models.ManyToManyField(through='flight.CalenderPrice', to='flight.Calender')),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.AddField(
            model_name='passengerinformation',
            name='boardings',
            field=models.ManyToManyField(through='flight.UserPassengerInformation', to='user.User'),
        ),
        migrations.AddField(
            model_name='passengerinformation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country'),
        ),
        migrations.AddField(
            model_name='passengerinformation',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gender'),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_time', models.DateTimeField()),
                ('arrive_time', models.DateTimeField()),
                ('depart_date', models.DateTimeField()),
                ('arrive_date', models.DateTimeField()),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('airplane_arrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_arrive', to='flight.airplane')),
                ('airplane_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_depart', to='flight.airplane')),
                ('airport_arrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive', to='flight.airport')),
                ('airport_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='flight.airport')),
                ('calender_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.calenderprice')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flightimage')),
                ('path_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.pathtype')),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.AddField(
            model_name='calenderprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.price'),
        ),
    ]
