# Generated by Django 3.1.4 on 2020-12-31 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20201230_0446'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airplane',
            table='airplanes',
        ),
    ]
